platform :ios, '13.0'

target 'MisoLynx' do
  # Lynx core + JS engine.
  pod 'Lynx', '4.0.0', :subspecs => ['Framework']
  pod 'PrimJS', '4.0.0', :subspecs => ['quickjs', 'napi']
  # Image / Log / Http services.
  pod 'LynxService', '4.0.0', :subspecs => ['Image', 'Log', 'Http']
  pod 'SDWebImage', '5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'
end
