import { diff } from './miso/dom';
import { eventJSON, delegateEvent, delegator } from './miso/event';
import { eventContext, drawingContext } from './miso/context/dom';
import { hydrate } from './miso/hydrate';

import {
   version,
   onBTS,
   onMTS,
   callFocus,
   callBlur,
   callSelect,
   callSetSelectionRange,
   fetchCore,
   websocketConnect,
   websocketClose,
   websocketSend,
   eventSourceConnect,
   eventSourceClose,
   populateClass,
   updateRef,
   inline,
   typeOf,
   mathRandom,
   getRandomValues,
   splitmix32,
   getDOMRef,
   cookieGet,
   cookieGetAll,
   cookieSet,
   cookieDelete,
   cookieDeleteWith,
} from './miso/util';

import {
    VTree,
    VNode,
    VText,
    VComp,
    Props,
    CSS,
    Events,
    NS,
    DOMRef,
    EventCapture,
    EventObject,
    Options,
    EventContext,
    DrawingContext,
    ComponentContext,
    HydrationContext,
    NodeId,
    VTreeType,
    ComponentId,
    Component,
    Runtime,
    PATCH,
    EVENT,
    InsertBefore,
    SwapDOMRefs,
    CreateElement,
    CreateElementNS,
    CreateTextNode,
    SetAttribute,
    SetAttributeNS,
    AppendChild,
    RemoveChild,
    ReplaceChild,
    RemoveAttribute,
    SetTextContent,
    SetInlineStyle,
    AddClass,
    RemoveClass,
    ProcessEvent,
    Flush,
    MountComponent,
    UnmountComponent,
    ModelHydration
} from './miso/types';

import { patch } from './miso/patch';

import { patchDrawingContext } from './miso/context/patch';
import { vcomp, vnode, vtext } from './miso/smart';

/* Top-level re-export */
export {

  /* Context */
  EventContext,
  DrawingContext,
  ComponentContext,
  HydrationContext,
  patchDrawingContext,

  /* Functions */
  eventContext,
  drawingContext,
  diff,
  delegator,
  hydrate,
  version,
  onBTS,
  onMTS,
  callBlur,
  callFocus,
  callSelect,
  callSetSelectionRange,
  eventJSON,
  fetchCore,
  websocketConnect,
  websocketClose,
  websocketSend,
  eventSourceConnect,
  eventSourceClose,
  patch,
  populateClass,
  updateRef,
  inline,
  typeOf,
  mathRandom,
  getRandomValues,
  splitmix32,
  delegateEvent,
  getDOMRef,
  cookieGet,
  cookieGetAll,
  cookieSet,
  cookieDelete,
  cookieDeleteWith,

  /* Types */
  VTree,
  VTreeType,
  VComp,
  VText,
  VNode,
  ComponentId,
  EventCapture,
  EventObject,
  Options,
  CSS,
  Props,
  Events,
  NS,
  DOMRef,
  NodeId,
  PATCH,
  EVENT,
  InsertBefore,
  SwapDOMRefs,
  CreateElement,
  CreateElementNS,
  CreateTextNode,
  SetAttribute,
  SetAttributeNS,
  AppendChild,
  RemoveChild,
  ReplaceChild,
  RemoveAttribute,
  SetTextContent,
  SetInlineStyle,
  AddClass,
  RemoveClass,
  ProcessEvent,
  Flush,
  MountComponent,
  UnmountComponent,
  ModelHydration,
  Runtime,
  Component,

  /* Smart constructors */
  vnode,
  vtext,
  vcomp
};
